### ISSUE TITLE
Authorize.net automatic endpoint detection is too slow

### ISSUE THREAD

**Issue by gavinwahl** [fusionbox/dinero#3]
The authorize.net gateway tries to auto-detect the correct endpoint url based on the credentials provided. This requires sending them a test request, which can take 5 seconds when they're having a bad day.  This makes the development server annoyingly slow, and means reloading code on the live server takes a long time as well.

If dinero was django specific, it would be very easy to cache this information, so authorize.net was only contacted when the credentials changed. I don't want to depend on django, though, so is there some other way to cache or make this faster?

**Comment by rockymeza** [comment]
We changed this to be lazy. start up time is no long slow (nor is it reliant on authorize.net to be up).
